name: bt_frontend
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.2.0
  image_picker: ^1.0.4
  curved_navigation_bar: ^1.0.3
  qr_flutter: ^4.1.0
  image: ^4.1.3
  url_launcher: ^6.1.14
  accordion: ^2.6.0
  date_field: ^3.0.5
  intl: ^0.18.1
  flutter_barcode_scanner: ^2.0.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  date_format: ^2.0.7
  provider: ^6.1.1
  animated_snack_bar: ^0.4.0
  cloudinary_flutter: ^1.1.0
  cloudinary_url_gen: ^1.3.0
  font_awesome_flutter: ^10.6.0
  carousel_slider: ^4.2.1
  fluentui_system_icons: ^1.1.223
  bot_toast: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/hotlines/
    - assets/images/

  fonts:
    - family: ProximaNova
      fonts:
        - asset: fonts/Proxima-Nova.otf
        - asset: fonts/Proxima-Nova-Bold.otf
          weight: 900

    - family: PoppinsSemiBold
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf

    - family: PoppinsLight
      fonts:
        - asset: fonts/Poppins-Light.ttf
